### ISSUE TITLE
Don't run complete CI on doc changes

### ISSUE THREAD

**Issue by ZuseZ4** [EnzymeAD/Enzyme#527]
Changes who only affect the documentation in the /doc folder should not affect the benchmarking or break the julia/rust/c++ tests, so we can skip most of the CI in that case, to reduce our runner workload further.

**Comment by tgymnich** [comment]
something like this would work:

```
on:
  push:
    paths-ignore:
      - 'docs/**'
```
